### ISSUE TITLE
Port updated Solvers functionality from MRTK

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/com.xrtk.core#260]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

MRTK recently updated Solver logic / code, to keep in line we should port / update the Solver logic

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5416

Ideally, this area still needs heavy rework to make it work more in the scriptableobject configuration approach, but for now, it should keep pace

## How would you classify your suggestion

- Architecture / Services

**Comment by hridpath** [comment]
This would be good, sooner than later. @StephenHodgson 😺

**Comment by StephenHodgson** [comment]
I got a great idea for this. 

I'd like to add a `IMixedRealitySover` interface with a lot of the public calls from the established classes.

Then have a solver system that works a lot like our service locator, that registers the solvers, giving them a priority and then sorting them, then calling update in a specific order.

**Comment by SimonDarksideJ** [comment]
I love this idea, I just want to clear some time to focus on solving this issue 😂
