### ISSUE TITLE
Review adoption patterns for XRTK - Full vs Individual components

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/com.xrtk.core#59]
## Is your feature request related to a problem? Please describe.
In discussions with adopters we are seeing multiple patterns for consuming the XRTK, from:

1. Brand new project
2. Existing project and upgrading (inc HTK)
3. Transferring from MRTK to XRTK
4. Isolating individual components to adopt in to another projects framework 

(List is not exhaustive and will likely increase with time)

## Describe the solution you'd like
Ultimately this proposal demands the need for multiple deployment options to address each of the above environments with several documented / supported deployment patterns, including:

1. Base deployment (already supported)
2. Existing project install (supported but needs better documentation)
3. Requires helpers to migrate the configuration utilised by an existing MRTK solution
4. Requires SDK components to be able to externalise services / components

## Additional context
This proposal marks the start of the discussion and prompts open discussion by all for any patterns we may have missed.

**Comment by StephenHodgson** [comment]
2 years on and I still have no idea what this task describes exactly 😅
