### ISSUE TITLE
Features Roadmap

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/com.xrtk.core#671]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

It was requested in a recent broadcast, that the community would like to see a public roadmap published to set expectations.

#ChallengeAccepted

---

An initial stab at the high-level roadmap - Need to create an infographic

## 0.2

- Updated to Unity 2019.4 LTS
- Hands Tracking for all supported platforms (HL2, Oculus, ML)
- Configuration stabilisation - Now platform specific
- Many stabilisation fixes
- New Platform system
- New Platform installer system (when new platforms added)
- Switch to GUID referenced assets, improves asset location and reduces compatibility issues
- Improved configuration screen designs
- Production status for foundation/core

## 0.3

- New UX system introduction
- New UX integration system introduction
- Universal Render Pipeline support
- Hands visualisation (Hands mesh / model control)
- Review Configuration system pattern
- Hands / input recording
- Platform commanding - cross-platform safe outbound interactions (Haptics / Overlays / services)
- Gltf improvements
- Unity 2020 compatibility

## 0.4

- Extension of UX / Interaction system
- Spatial Understanding
- Spatial Awareness
- IoT integration
- Spacewalk demonstration 
- XRTK Academy/University courses

## Ongoing tasks

- New Platform additions - UltraLeap / SteamVR / Lenovo / nReal / etee
- Stabilisation / review
- New Interaction systems and extension services
- Vendor integration

**Comment by StephenHodgson** [comment]
Isn't this what https://github.com/XRTK/XRTK-Core/projects is for?

**Comment by SimonDarksideJ** [comment]
That is the internal project view @StephenHodgson , but the community have asked for a more public-facing roadmap/infographic to be crystal clear.  Going to work on this in the week, plus update our projects view/tasks

**Comment by StephenHodgson** [comment]
Yeah I suppose I could see it being difficult to track projects across all of our repos.

**Comment by SimonDarksideJ** [comment]
https://media.discordapp.net/attachments/665107384267571210/781547708321235024/unknown.png
Initial infographic for the roadmap

**Comment by StephenHodgson** [comment]
I still don't think we should assign deadlines to these, or any kind of temporal agreement.

**Comment by SimonDarksideJ** [comment]
I'll add comments to the official roadmap page that these are summary guidelines and not contractual deliverables. We can update as needed.
But as a roadmap, we should indicate some sort of timeframe.  If quarters are still too low level, we can just specify years.   but I will state, these aren't cast in stone, just advisories.
