### ISSUE TITLE
Extension Services tests need to be updated

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/com.xrtk.core#869]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Found during the implementation of an Extension Service with several Extension Data Providers, the Data Providers were never registering with their host services.

Updated the Unity Tests in the base project to confirm and found this is a core issue in how extension services are found.  Unit test 05_10 now confirms there is an issue.

The Extension Service setup now matches the same setup for a "Core" system, except using the base "extension" versions of interfaces:

- IMixedRealityService -> IMixedRealityExtensionService 
- IMixedRealityDataProvider -> IMixedRealityExtensionDataProvider 

Both implementations and tests are identical, however, produce different results and the Extension variant fails tests.

## To Reproduce

1. Run test 05_10 in Tests Branch #868

## Expected behavior
Test should pass

## Actual behavior
Test fails as the Extension Data Provider is unable to be registered correctly and does not bond with it's host service

**Comment by StephenHodgson** [comment]
Pretty sure this is just an implementation detail of the tests or specific systems/services. 

Core systems and services are working as intended.
