### ISSUE TITLE
Find a more suitable name for MixedRealityPlayspace

### ISSUE THREAD

**Issue by FejZa** [XRTK/com.xrtk.core#896]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

As discussed in Discord feedback I keep hearing is that people do not understand the "MixedRealityPlayspace". Most prominent questions are:

- When I want to move the player, do I move the "Playspace"?
- Do I put all of my scene content into the "Playspace"?
- Why isn't it called "Player"?

So I wanna suggest renaming the playspace object. My suggestions for more suitable and self-speaking names are:

- XRRig
- XRPlayer
- Player
- XRCameraRig

**Comment by SimonDarksideJ** [comment]
![image](https://media.tenor.co/images/83f2e6b49b55d7a05ffb07344f2b35a9/raw)

**Comment by FejZa** [comment]
Implemented in #898
