### ISSUE TITLE
Feature Request: Separate the Service Locator dependency in to its own feature

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/com.xrtk.core#918]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

The Service Locator is a core part that is consumed by the XRTK but it is useful in itself to other Unity projects without the overhead of the XRTK itself.
Several projects have been noted to be consuming all of the core of the XRTK, just to use the Service Locator feature.

## How would you classify your suggestion

- Architecture / Services

## Describe the solution you'd like

The Service Locator functionality itself should be broken out in to it's own separate project and the XRTK core project updated to use this as a dependency.

This would greatly reduce the impacts for customers only using the service locator feature.

**Comment by SimonDarksideJ** [comment]
Thoughts @StephenHodgson given you have projects that are using the locator but not the XRTK itself.

**Comment by StephenHodgson** [comment]
It's like asking a Tiger to lose its stripes. That's pretty much the heart of what makes the XRTK what it is.
